#!/usr/bin/env bash

# laughable simple placholder script for edp build

# shift the "build" command from edp build
shift

while [[ $# -gt 0 ]]; do
    case $1 in
        --target)
            target=$2
            shift 2
            # shellcheck disable=SC2210
            ! [[ -d "$target" ]] && echo "target: $target not a dir" 1>2 && exit 1
        ;;
    esac
done

# put some random ahh file for the test
(cd "$target" && touch index.php )

# then echo the dir

echo "$target"
