#!/usr/bin/env bash

# laughable simple placholder script for edp build

# shift the "build" command from edp build
shift

while [[ $# -gt 0 ]]; do
    case $1 in
        --target)
            target=$2
            shift 2
        ;;
        --silent)
            # this mock edp is silent by default but lets parse it to adhere to the spec/cli
            shift 1
        ;;
    esac
done

mkdir -p "$target"

# just move everything to the target; this is a mock script the real edp your responsible for providing it.

cp ./* "$target"

echo "$target"
