[git]
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^doc", group = "Documentation" },
  { message = "^refactor", group = "Code Improvements" },
]

[changelog]
header = "== Changelog ==\n"
body = """
{% if version -%}
= {{ version | trim_start_matches(pat="v") }} =
{% else -%}
= Unreleased =
{% endif -%}

{% for group, commits in commits | group_by(attribute="group") -%}
**{{ group | replace(from="1_", to="") | replace(from="2_", to="") | replace(from="3_", to="") }}**
{% for commit in commits -%}
* {{ commit.message | upper_first }}
{% endfor -%}

{% endfor -%}
"""
trim = false

