name: CI Smoke Tests

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    # ==============================================================================
    #  Set if we have changed PHP files
    # ==============================================================================
    set-php-has-changes:
      name: Check for PHP file changes
      runs-on: ubuntu-latest
      outputs:
        has_php: ${{ steps.php-changes.outputs.php }}
      steps:
        - uses: actions/checkout@v4
        - uses: dorny/paths-filter@v3
          id: php-changes
          with:
            filters: |
              php:
                - '**/*.php'
    # ==============================================================================
    #  Then only check for syntax errors on changed PHP files
    # ==============================================================================    
    check-php-changed-files:
        name: Ensure changed PHP files are valid across all supported PHP versions.
        needs: set-php-has-changes
        if: needs.set-php-has-changes.outputs.has_php == 'true'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php-version: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
        steps:
            # ------------------------------------------------
            #  setup...
            # ------------------------------------------------
            - uses: actions/checkout@v6

            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.37.2
              with: 
                php-version: ${{ matrix.php-version }}
                coverage: none

            # --------  set changed files --------
            - name: Set changed PHP files
              id: changed-php-files
              uses: tj-actions/changed-files@v47.0.6
              with: 
                files: |
                    **.php
            # ------------------------------------------------
            #  Run the actual lint checks!
            # ------------------------------------------------
            #- run: echo "${{ steps.changed-php-files.outputs.all_changed_files }}"
            - name: Check changed files syntax
              run: |
                for file in ${{ steps.changed-php-files.outputs.all_changed_files }}; do
                    php -l "$file"
                done
    # ==============================================================================
    #  Now lets build the initial artifact, without compiling js 
    # ==============================================================================
    initial-build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: check-php-changed-files
      if: always() && (needs.check-php-changed-files.result == 'success' || needs.check-php-changed-files.result == 'skipped')
      steps:
        - uses: actions/checkout@v4
        # ------------------------------------------------
        #  create base initial build, lacks some transformations and js compilation
        # ------------------------------------------------
        - name: Run the edp builder
          id: edp-build
          run: |
            # ion know if is exec so lets ensure it is
            chmod u+x ./edp
            
            buildDir=$(./edp build --target $RUNNER_TEMP/build --silent)
            echo "buildDir=$buildDir" >> $GITHUB_OUTPUT
        # ------------------------------------------------
        #  Save it to a new tmp branch for testing
        # ------------------------------------------------
        - name: Deploy build output to dynamic preview branch
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ${{ steps.edp-build.outputs.buildDir }}
            branch: build-preview-pr-${{ github.event.number }}
