name: CI Smoke Tests

on: 
  pull_request:
    paths-ignore:
      - '.github/**'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    # ==============================================================================
    #  Set if we have changed PHP files
    # ==============================================================================
    set-php-has-changes:
      name: Check for PHP file changes
      runs-on: ubuntu-latest
      outputs:
        has_php: ${{ steps.php-changes.outputs.php }}
      steps:
        - uses: actions/checkout@v4
        - uses: dorny/paths-filter@v3
          id: php-changes
          with:
            filters: |
              php:
                - '**/*.php'
    # ==============================================================================
    #  Then only check for syntax errors on changed PHP files
    # ==============================================================================    
    check-php-changed-files:
        name: Ensure changed PHP files are valid across all supported PHP versions.
        needs: set-php-has-changes
        if: needs.set-php-has-changes.outputs.has_php == 'true'
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                # php-version: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]
                php-version: [7.4]
        steps:
            # ------------------------------------------------
            #  setup...
            # ------------------------------------------------
            - uses: actions/checkout@v6

            - name: Setup PHP Action
              uses: shivammathur/setup-php@2.37.2
              with: 
                php-version: ${{ matrix.php-version }}
                coverage: none

            # --------  set changed files --------
            - name: Set changed PHP files
              id: changed-php-files
              uses: tj-actions/changed-files@v47.0.6
              with: 
                files: |
                    **.php
            # ------------------------------------------------
            #  Run the actual lint checks!
            # ------------------------------------------------
            #- run: echo "${{ steps.changed-php-files.outputs.all_changed_files }}"
            - name: Check changed files syntax
              run: |
                for file in ${{ steps.changed-php-files.outputs.all_changed_files }}; do
                    [ -f "$file" ] && php -l "$file"
                done
    # ==============================================================================
    #  Now lets build the initial artifact, without compiling js 
    # ==============================================================================
    initial-build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      needs: check-php-changed-files
      if: always() && (needs.check-php-changed-files.result == 'success' || needs.check-php-changed-files.result == 'skipped')
      steps:
        # ==============================================================================
        #  Setup the env...
        # ==============================================================================
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        # --------  fetch all them tags --------
        - name: Fetch Git Tags
          run: git fetch --tags
        
        # --------  add the local bin to path --------
        - name: Add ~/.local/bin to the path PATH, used by some deps bellow
          run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # --------  install php 8.4 --------
        - name: Setup PHP Action
          uses: shivammathur/setup-php@2.37.2
          with: 
            php-version: 8.4
            coverage: none
        
        # --------  set wp version to use (latest) --------
        - name: Set WP version to use
          id: wp-version
          run: |
            echo "wpVersion=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')" >> $GITHUB_OUTPUT
        
        # --------  Install versions finder --------
        - name: Install versions-finder
          run: |
            curl -L https://raw.githubusercontent.com/neblabs/versions-finder/main/install.sh | bash
            # fails if not found
            command -v versions-finder
          
        # ------------------------------------------------
        #  create base initial build, lacks some transformations and js compilation
        # ------------------------------------------------
        - name: Run the edp builder
          id: edp-build
          run: |
            # ion know if is exec so lets ensure it is
            chmod u+x ./edp
            
            buildDir=$(./edp build --target $RUNNER_TEMP/build --silent)
            echo "buildDir=$buildDir" >> $GITHUB_OUTPUT
        # ------------------------------------------------
        #  Inject the headers into the build
        # ------------------------------------------------
        - name: Inject headers data
          run: |
            curl -L https://raw.githubusercontent.com/neblabs/header-injector/main/bin/install.sh | bash
            # fails if not found
            command -v header-injector

            # inject it
            res=$(header-injector inject . "${{ steps.edp-build.outputs.buildDir }}" "${{ steps.wp-version.outputs.wpVersion }}" --git-source .)

            { read -r phpFile; read -r readmeFile; } <<< "$res"

            #validate it
            header-injector validate "$phpFile" "$readmeFile" "${{ steps.wp-version.outputs.wpVersion }}" --git-source .
        # ------------------------------------------------
        #  Now for the changelog
        # ------------------------------------------------
        # --------  lets setup git cliff here so that if something failed earlier we are not wasting extra time. --------
        - name: Set up git-cliff
          uses: kenji-miyake/setup-git-cliff@v1

        - name: Inject changelog data
          run: |
            curl -L https://raw.githubusercontent.com/neblabs/wp-changelog-injector/main/install.sh | bash
            
            # fails if not found
            command -v wp-changelog-injector

            # on pull request get the changelog from the latest tag instead of the previous which is for on tags push.
            if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
              # this flag is passed to wp-changelog-injector
              latest=--latest
            fi

            bash -x wp-changelog-injector --readme "${{ steps.edp-build.outputs.buildDir }}"/readme.md --changelog "${{ steps.edp-build.outputs.buildDir }}"/changelog.md "$latest"
            
        # ------------------------------------------------
        #  Save it to a new tmp branch for testing 
        # ------------------------------------------------
        - name: Deploy build output to dynamic preview branch
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: ${{ steps.edp-build.outputs.buildDir }}
            branch: build-preview-pr-${{ github.event.number }}-${{ github.run_id }}
        # ------------------------------------------------
        #  Now the plugin check tests
        # ------------------------------------------------
        - name: Create wp-env config overrides
          run: |
            cat << EOF > .wp-env.override.json
            {
              "core": "https://wordpress.org/wordpress-${{ steps.wp-version.outputs.wpVersion }}.zip",
              "config": {
                "WP_DEBUG": true,
                "WP_DEBUG_DISPLAY": false,
                "WP_DEBUG_LOG": true
              }
            }
            EOF

        - name: Cache wp-env assets by WP version
          uses: actions/cache@v4
          with:
            path: ~/.wp-env
            key: wp-env-${{ runner.os }}-wp-${{ steps.wp-version.outputs.wpVersion }}
            restore-keys: |
              wp-env-${{ runner.os }}-wp-

        - name: Run plugin check
          uses: wordpress/plugin-check-action@v1
          with:
            build-dir: ${{ steps.edp-build.outputs.buildDir }}
            ignore-codes: |
              no_stable_tag
