name: PR smoke tests workflow call test

on: 
  pull_request:
    paths-ignore:
      - '.github/**'

permissions:
    contents: write
    pull-requests: write

jobs:
    call_smoke_tests_workflow:
        uses: rafark/cicd-labs/.github/workflows/smoke-tests.yml@main
